const mongoose = require('mongoose');
const DB_CONSTANT = require('../DB_Names');
const schema = mongoose.Schema; 

const centralMedicineDB = new schema({
    productId:{
        type: String,
        required:true,
    },
    name:{
        type:String,
        required:true,
    },
    manufacturer:{
        type:String,
        required:true,
    },
    saltComposition:{
        type:String,
        required:true,
    },
    medicineType:{
        type:String,
        required:true,
    },
    introduction:{
        type:String,
        required:true,
    },
    benifits:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    howToUse:{
        type:String,
        required:true,
    },
    safetyAdvice:{
        type:String,
        required:true,
    },
    ifMiss:{
        type:String,
        required:true,
    },
    packagingDetails:{
        type:String,
        required:true,
    },
    package:{
        type:String,
        required:true,
    },
    quantity:{
        type:String,
        required:true,
    },
    productForm:{
        type:String,
        required:true,
    },
    MRP:{
        type:String,
        required:true,
    },
    manufacturer:{
        type:String,
        required:true,
    },
    prescriptionRequired:{
        type:String,
        required:true,
    },
    factBox:{
        type:String,
        required:true,
    },
    primaryUsage:{
        type:String,
        required:true,
    },
    storage:{
        type:String,
        required:true,
    },
    useOf:{
        type:String,
        required:true,
    },
    commonSideEffects:{
        type:String,
        required:true,
    },
    alcholInteractions:{
        type:String,
        required:true,
    }, 
    pregnancyInteractions:{
        type:String,
        required:true,
    },
    lactationInteractions:{
        type:String,
        required:true,
    },
    drivingInteractions:{
        type:String,
        required:true,
    },
    kidneyInteractions:{
        type:String,
        required:true,
    },
    liverInteractions:{
        type:String,
        required:true,
    },
    manufacturerAddress:{
        type:String,
        required:true,
    },
    howItWork:{
        type:String,
        required:true,
    },
    marketerDetails:{
        type:String,
        required:true,
    },
    productImage:{
        type:String,
        required:true,
    }
});

//define any methods you want to define on this schema
//schemaName.methods.methodName
DB_CONSTANT.CENTRAL_MEDICINE_DB
module.exports = mongoose.model(DB_CONSTANT.CENTRAL_MEDICINE_DB,centralMedicineDB,DB_CONSTANT.CENTRAL_MEDICINE_DB);